language: java

sudo: required
dist: trusty
group: edge
jdk: oraclejdk9

env:
  - RXJAVA_TARGET=1.6
  - RXJAVA_TARGET=1.8
  - RXJAVA_TARGET=1.9

#jdk:
#  - oraclejdk9

before_install:
  - chmod +x gradlew
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - export GRADLE_OPTS=-Xmx1024m
#  - cd ~
#  - wget http://download.java.net/java/jdk9/archive/181/binaries/jdk-9+181_linux-x64_bin.tar.gz
#  - tar -xzf jdk-9+181_linux-x64_bin.tar.gz
#  - export JAVA_HOME=~/jdk-9
#  - PATH=$JAVA_HOME/bin:$PATH
#  - cd -

after_success:
  - bash <(curl -s https://codecov.io/bash)

 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
